FROM python:3.11-slim

WORKDIR /app

RUN apt-get update \
 && apt-get install -y ffmpeg \
 && rm -rf /var/lib/apt/lists/*

COPY requirements_bot.txt .
RUN pip install --no-cache-dir -r requirements_bot.txt

COPY . .

ENV PYTHONUNBUFFERED=1

CMD ["python", "bot.py"]
