version: "3.1"
config:
  recipe: default.v1

language: ru

pipeline:
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-multilingual-cased"
- name: DIETClassifier
  epochs: 50
  embedding_dimension: 256
  constrain_similarities: true
  batch_size: [32, 64]
  learning_rate: 0.005
  random_seed: 42
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 30
  constrain_similarities: true
assistant_id: 20250427-045642-salty-market
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
  - name: RulePolicy
